version: "3.3"
services:
  ghub-api:    
    container_name: ghub-api
    build:      
      context: .
      dockerfile: ./Dockerfile
    depends_on: [ mssql ]    
    environment:
      - AppSettings__ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=GHub;User Id=sa;Password=e@zx2Prn9mj4zU3ap8WV7ckNK;
    ports:
      - "8080:80"
    restart: unless-stopped
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    hostname: mssql 
    environment:
      SA_PASSWORD: "e@x2Prn9mj4zU3ap8WV7ckNK"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    user: root
    volumes:
      - mssql_volume:/var/opt/mssql/data
      - mssql_volume:/var/backups
volumes:
  mssql_volume:
    driver: local