version: "3.3"
services:
  ghub-api:    
    container_name: ghub-api
    environment:
      - AppSettings__ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=GHub;User Id=sa;Password=d@nielng;TrustServerCertificate=true;
    build:      
      context: .
      dockerfile: ./Dockerfile
    depends_on: [ mssql ]    
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    container_name: mssql
    hostname: mssql 
    environment:
      SA_PASSWORD: "d@nielng"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - mssql_volume:/var/opt/mssql/data
      - mssql_volume:/var/backups
volumes:
  mssql_volume:
    driver: local
  